theme: jekyll-theme-cayman
title: Facteur
description: The mailing kit for .NET
color:
  header: "#ffffff"
  gradient_left: "#229dfb"
  gradient_right: "#10d797"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css